### NumPy Lab

Name: Addison Zheng

### <span style="color:red">Task 1</span>

Use the appropriate NumPy methods to do the following: Fill a 2-by-3 array with ones, a 3-by-3 array with zeros and a 2-by-5 array with 5s. Display each array.

In [10]:
import numpy as np

array2x3 = np.ones((2,3))
array3x3 = np.zeros((3,3))
array2x5 = np.full((2,5),5)

print('array2x3:',array2x3)
print('array3x3:',array3x3)
print('array2x5:',array2x5)

array2x3: [[1. 1. 1.]
 [1. 1. 1.]]
array3x3: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array2x5: [[5 5 5 5 5]
 [5 5 5 5 5]]


### <span style="color:red">Task 2</span>

Use arange to create an array containing the values 1-15, reshape it into a 3 by 5 array, then use indexing and slicing techniques to perform each of the following operations :
* Select and display the 3rd row
* Select and display the 4th column
* Select and display the first and second row.
* Select and display the 2nd column up to and including the 4th column
* Select and display the element that is in the 2nd row and the 4th column
* Select and display all the elements from the 1st and 2nd row and the first column, the 3rd column, and the 5th column.

Remember, rows and columns start indexing at 0.  When asked to display the 2nd row, you should display the row with the index of 1. The same applies to columns.


In [35]:
array3x5 = np.arange(1,16).reshape(3,5)
print(array3x5,'\n')

print('3rd row\n', array3x5[2])
print('4th column\n', array3x5[:, 3])
print('1st & 2nd row\n', array3x5[0:2])
print('2nd-4th col\n', array3x5[:,1:4])
print('1st & 2nd row\n', array3x5[0:2], '\n1st col\n',array3x5[:, 0], '\n3rd col\n',array3x5[:, 2], '\n5th col\n',array3x5[:, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

3rd row
 [11 12 13 14 15]
4th column
 [ 4  9 14]
1st & 2nd row
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd-4th col
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
1st & 2nd row
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 
1st col
 [ 1  6 11] 
3rd col
 [ 3  8 13] 
5th col
 [ 5 10 15]


### <span style="color:red">Task 3</span>

Use arange to create a 2-by-2 array containing the numbers 0–3. Use **broadcasting** to perform each of the following operations on the **original** array :

* Square every element of the array.

* Add 6 to every element of the array.

* Multiply every element of the array by 3.

Make sure you display the results.

In [42]:
array2x2 = np.arange(0,4).reshape(2,2)
print('orig\n', array2x2)
print('**2\n',array2x2 ** 2)
print('+6\n', array2x2 + 6)
print('*3\n', array2x2 * 3)

orig
 [[0 1]
 [2 3]]
**2
 [[0 1]
 [4 9]]
+6
 [[6 7]
 [8 9]]
*3
 [[0 3]
 [6 9]]


### <span style="color:red">Task 4</span> 

Use arange to create a 3-by-3 array containing the even integers from 2 through 18. Use arange to create a second 3-by-3 array containing the integers from 9 down to 1, then multiply the first array by the second.

In [52]:
array3x3_1 = np.arange(2,19, 2).reshape(3,3)
array3x3_2 = np.arange(9,0, -1).reshape(3,3)
print('Array 1\n', array3x3_1)
print('Array 2\n', array3x3_2)

print('Array 3\n', array3x3_1 * array3x3_2)

Array 1
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Array 2
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Array 3
 [[18 32 42]
 [48 50 48]
 [42 32 18]]


### <span style="color:red">Task 5</span> 
 
Use a list comprehenstion to create a 2-by-3 array containing the first six powers of 2 beginning with 2<sup>0</sup>. Flatten the array first with method ```flatten```, then with ```ravel```. In each case, display the result then display the original array to show that it was unmodified.

<span style ="color:red">Answer this question in markdown: What is the difference between flatten and ravel?

Flatten creates a 1-d copy of the original array while ravel trys to create a 1-d view of the original matrix